### ISSUE TITLE
入学篇中若干错误或建议

### ISSUE THREAD

**Issue by AllanChain** [xiaotianxt/rookie-in-pku#1]
- 20 级应该是 `@stu.pku.edu.cn` 了
- Win10 家庭版也有 WSL 吧
- 赵老师的课可能不再有炒股和交谊舞了

BTW，不错的文章，蹲设备联动部分

**Comment by xiaotianxt** [comment]
1. 确实改了，但是20届或许都不是从its里面更改别名了（不是用的网易服务吗），所以我只好按照我能了解到的写。
2. 我真的没怎么用过家庭版，WSL是我猜测的哈哈。
3. 赵老师依然在微信群中分享炒股经验👻

**Comment by AllanChain** [comment]
以及 “级” vs “届” :smile:

**Comment by xiaotianxt** [comment]
噗哈哈哈，我改我改
