### ISSUE TITLE
WallessPKU Data Quota

### ISSUE THREAD

**Issue by hiaoxui** [xiaotianxt/rookie-in-pku#2]
在入学篇 `你也许不知道的BBS福利` section 中, 有提到 @hiaoxui 提供科学上网服务. 但是流量限制并不是每月 20G. 严格来说是 balance 上限是 20G, 每天补充 2G, 且不同服务器会有不同的计算权重. 

感谢宣传.

**Comment by xiaotianxt** [comment]
哈哈好的，我会在文中重新描述。
不知道该叫你xiaohui还是hiaoxui😂

**Comment by hiaoxui** [comment]
称呼我为 hiaoxui 就好了, xiaohui 太容易重名. (但不是 hiaoxu)

那倒也不必如此详细, 太占用你的版面了. 不如这样:

... 志愿提供，有较为宽裕的流量限制 （2G/天，非热门地区服务节点降权计算），有针对北大设置的服务器线路和代理规则。对科学上网没有强烈需求的同学可以考虑申请使用。

**Comment by hiaoxui** [comment]
可以麻烦彻底删掉这个 issue 吗? 感谢.

**Comment by xiaotianxt** [comment]
好的
